# Configuration using computing features of extracted RGB patches guided by openpose skeleton keypoints.
# In this mode, there is a feature vector for specific body part groups (e.g. head, torso, arms, legs)

input_data:
  - path: ../preprocessed_data/UTD-MHAD/rgb_group_patch_features_op
    loader: NumpyDatasetLoader

out_path: ../models/mmargcn/UTD-MHAD
model: mmargcn
dataset: UTD-MHAD
session_type: training
fixed_seed: 1

mode: rgb_patch_groups_features
model_args:
  rgb_patch_groups_edges:
    - 1, 0
    - 2, 0
    - 3, 0
    - 4, 0
    - 1, 2
    - 3, 4

base_lr: 0.001
optimizer: ADAM
optimizer_args:
  weight_decay: 0.01

lr_scheduler: ca

batch_size: 8
epochs: 50
