# Configuration with same parameters as in AGCN paper/code (except batch size)

input_data:
  - path: ../preprocessed_data/MMAct/skeleton_default/cross_subject
    loader: NumpyDatasetLoader

out_path: ../models/mmargcn/MMAct
model: agcn
dataset: MMAct
session_type: training
fixed_seed: 1

base_lr: 0.1
optimizer: SGD
optimizer_args:
  momentum: 0.9
  nesterov: true
  weight_decay: 0.0001

lr_scheduler: multistep
lr_scheduler_args:
  milestones:
    - 20
    - 28
  gamma: 0.1

batch_size: 8
epochs: 35
