
input_data:
  - path: ..\preprocessed_data\UTD-MHAD\skeleton_default
    loader: NumpyDatasetLoader
    loader_args:
      in_memory: True
  - path: ..\preprocessed_data\UTD-MHAD\imu_signal_image
    loader: NumpyDatasetLoader
    loader_args:
      in_memory: True

out_path: ..\models\mmargcn\UTD-MHAD
model: mmargcn
dataset: UTD-MHAD
session_type: training
fixed_seed: 1

mode: skeleton_imu_gcn_late_fusion
model_args:
  graph_node_format: node_per_sensor
  num_signals: 2
  gc_model: agcn
  fusion: concatenate

base_lr: 0.001
optimizer: ADAM
optimizer_args:
  weight_decay: 0.01

lr_scheduler: ca

batch_size: 8
epochs: 50
