# Configuration using Skeleton+IMU data combined
# IMU signals (e.g. acc, gyro) are appended to the skeleton as additional joints
# For V2: IMU joints are appended both the right wrist and the right hip
# interconnect: All imu joints have connections to each other

input_data:
  - path: ..\preprocessed_data\MMAct\skeleton_imu_enhanced\cross_subject
    loader: NumpyDatasetLoader

out_path: ..\models\mmargcn\MMAct
model: mmargcn
dataset: MMAct
session_type: training
fixed_seed: 1

mode: skeleton_imu_enhanced
model_args:
  num_imu_joints: 2
  imu_enhanced_mode: append_right
  right_wrist_joint: 10
  right_hip_joint: 16
  interconnect_imu_joints: True

base_lr: 0.1
optimizer: SGD
optimizer_args:
  momentum: 0.9
  nesterov: true
  weight_decay: 0.0001

lr_scheduler: multistep
lr_scheduler_args:
  milestones:
    - 30
    - 40
  gamma: 0.1

batch_size: 8
epochs: 50
