# Create a graph from each individual RGB frame.
# The RGB frame is first fed to a 2D CNN. The pooled output of that 2D CNN will be used as graph input for AGCN.

input_data:
  - path: ..\preprocessed_data\UTD-MHAD\skeleton_imu_enhanced__rgb_default
    loader: NumpyDatasetLoader

out_path: ..\models\mmargcn\UTD-MHAD
model: mmargcn
dataset: UTD-MHAD
session_type: training
fixed_seed: 1

mode: skeleton_imu_rgb_cnn_encoder_early_fusion
model_args:
  fusion: concatenate
  num_imu_joints: 2
  imu_enhanced_mode: append_center

base_lr: 0.001
optimizer: ADAM
optimizer_args:
  weight_decay: 0.01

lr_scheduler: ca

batch_size: 8
epochs: 50
