# Combine skeleton+imu augment_v1 with R2P1D RGB embeddings

input_data:
  - path: ..\preprocessed_data\UTD-MHAD\skeleton_imu_enhanced__rgb_default
    loader: NumpyDatasetLoader

out_path: ..\models\mmargcn\UTD-MHAD
model: mmargcn
dataset: UTD-MHAD
session_type: training
fixed_seed: 1

mode: skeleton_imu_rgb_r2p1d_early_fusion
grad_accum_step: 4
model_args:
  num_imu_joints: 2
  imu_enhanced_mode: append_center

base_lr: 0.001
optimizer: ADAM
optimizer_args:
  weight_decay: 0.01

lr_scheduler: ca

batch_size: 8
epochs: 50
