# Use pretrained R(2+1)D network on RGB data.
# Format output so that it can be fused with skeleton data and processed in AGCN.

input_data:
  - path: ..\preprocessed_data\UTD-MHAD\skeleton_default__rgb_default
    loader: NumpyDatasetLoader

out_path: ..\models\mmargcn\UTD-MHAD
model: mmargcn
dataset: UTD-MHAD
session_type: training
fixed_seed: 1

mode: skeleton_rgb_encoding_r2p1d_early_fusion
grad_accum_step: 4

base_lr: 0.001
optimizer: ADAM
optimizer_args:
  weight_decay: 0.01

lr_scheduler: ca

batch_size: 8
epochs: 50
