in_path: ..\preprocessed_data\UTD-MHAD
out_path: ..\models\agcn\UTD-MHAD
model: agcn
session_type: training
dataset: utd_mhad

base_lr: 0.01
optimizer: SGD
optimizer_args:
  momentum: 0.9
  nesterov: true
  weight_decay: 0.0001

lr_scheduler: multistep
lr_scheduler_args:
  milestones:
    - 40
    - 45
  gamma: 0.1

batch_size: 24
epochs: 50
