in_path: ..\preprocessed_data\UTD-MHAD
out_path: ..\models\agcn\UTD-MHAD
model: agcn
dataset: UTD-MHAD
session_type: training

base_lr: 0.0006
optimizer: ADAM
optimizer_args:
  weight_decay: 0.01

lr_scheduler: ca

batch_size: 8
epochs: 50
