in_path: ..\preprocessed_data\UTD-MHAD
out_path: ..\models\agcn\UTD-MHAD
model: agcn
session_type: training
dataset: utd_mhad

base_lr: 0.005
optimizer: ADAM
# optimizer_args:
#   momentum: 0.9
#   nesterov: true
#   weight_decay: 0.01

lr_scheduler: onecycle
lr_scheduler_args:
  max_lr: 0.01
# lr_scheduler_args:
#   milestones:
#     - 10
#     - 20
#     - 30
#   gamma: 0.1

batch_size: 8
epochs: 50
