# Configuration using Skeleton+IMU data combined and extracted and computed RGB patch features

in_path: ..\preprocessed_data\UTD-MHAD\skele+imu
out_path: ..\models\agcn\UTD-MHAD
model: mmagcn
dataset: UTD-MHAD
session_type: training
loader: loader.SkeletonDataset
fixed_seed: 1

mode: skele+imu

base_lr: 0.001
optimizer: ADAM
optimizer_args:
  weight_decay: 0.01

lr_scheduler: ca

batch_size: 8
epochs: 50
