# Configuration using Skeleton+IMU data combined and extracted and computed RGB patch features

in_path: ..\preprocessed_data\UTD-MHAD\skele+imu__rgb_patches_op
out_path: ..\models\agcn\UTD-MHAD
model: mmagcn
dataset: UTD-MHAD
session_type: training
loader: loader.SkeletonRGBPatchFeaturesDataset
fixed_seed: 1

mode: skele+imu__rgb_patches_op

base_lr: 0.0005
optimizer: SGD
optimizer_args:
  momentum: 0.9
  nesterov: true
  weight_decay: 0.01

lr_scheduler: exp
lr_scheduler_args:
  gamma: 0.95

batch_size: 8
epochs: 50
