
input_data:
  - path: ../preprocessed_data/UTD-MHAD/skeleton_default
    loader: NumpyDatasetLoader
  - path: ../preprocessed_data/UTD-MHAD/rgb_default
    loader: NumpyDatasetLoader

out_path: ../models/mmargcn/UTD-MHAD
model: mmargcn
dataset: UTD-MHAD
session_type: training
fixed_seed: 1

mode: skeleton_rgb_r2p1d_late_fusion
model_args:
  fusion: concatenate

base_lr: 0.001
optimizer: ADAM
optimizer_args:
  weight_decay: 0.01

lr_scheduler: ca

batch_size: 8
epochs: 50
