# Configuration with same parameters as in AGCN paper/code (except batch size)

input_data:
  - path: ../preprocessed_data/UTD-MHAD/skeleton_default
    loader: NumpyDatasetLoader
    loader_args:
      in_memory: True

out_path: ../models/mmargcn/UTD-MHAD
model: agcn
dataset: UTD-MHAD
session_type: training
fixed_seed: 1

base_lr: 0.1
optimizer: SGD
optimizer_args:
  momentum: 0.9
  nesterov: true
  weight_decay: 0.0001

lr_scheduler: multistep
lr_scheduler_args:
  milestones:
    - 30
    - 40
  gamma: 0.1

batch_size: 8
epochs: 50
