# Run AGCN on skeleton data with different hyperparameters than in original AGCN paper/code

input_data:
  - path: ..\preprocessed_data\UTD-MHAD\skeleton_default
    loader: NumpyDatasetLoader
    loader_args:
      in_memory: True

out_path: ..\models\mmargcn\UTD-MHAD
model: agcn
dataset: UTD-MHAD
session_type: training
fixed_seed: 1

base_lr: 0.001
optimizer: ADAM
optimizer_args:
  weight_decay: 0.01

lr_scheduler: ca

batch_size: 8
epochs: 50
