fixed_seed: 1

in_path: ..\preprocessed_data\NTU-RGB-D\xview
out_path: ..\models\agcn\NTU-RGB-D\xview
model: agcn
session_type: training
dataset: ntu_rgb_d

base_lr: 0.1
optimizer: SGD
optimizer_args:
  momentum: 0.9
  nesterov: true
  weight_decay: 0.0001

lr_scheduler: multistep
lr_scheduler_args:
  milestones:
    - 30
    - 40
  gamma: 0.1

batch_size: 10
epochs: 50
