fixed_seed: 1

input_data:
  - path: ..\preprocessed_data\NTU-RGB-D\xview\skeleton_default
    loader: NumpyDatasetLoader
    loader_args:
      in_memory: True

out_path: ..\models\agcn\NTU-RGB-D\xview
model: agcn
dataset: NTU-RGB-D
session_type: training

base_lr: 0.1
optimizer: SGD
optimizer_args:
  momentum: 0.9
  nesterov: true
  weight_decay: 0.0001

lr_scheduler: multistep
lr_scheduler_args:
  milestones:
    - 30
    - 40
  gamma: 0.1

batch_size: 10
epochs: 50
