# IMU sequence (num_frames, 6) is treated as a graph with num_frames * 6 nodes
# and processed in a GCN

input_data:
  - path: ..\preprocessed_data\UTD-MHAD\imu_default
    loader: NumpyDatasetLoader

out_path: ..\models\mmargcn\UTD-MHAD
model: mmargcn
dataset: UTD-MHAD
session_type: training
fixed_seed: 1

mode: imu_gcn

base_lr: 0.001
optimizer: ADAM
optimizer_args:
  weight_decay: 0.01

lr_scheduler: ca

batch_size: 8
epochs: 50
