# IMU sequence (num_frames, 6) is treated as a graph with num_frames * 2 nodes
# (one node for acc + one node for gyro for each time step) and processed in a GCN

input_data:
  - path: ..\preprocessed_data\UTD-MHAD\imu_default
    loader: NumpyDatasetLoader

out_path: ..\models\mmargcn\UTD-MHAD
model: mmargcn
dataset: UTD-MHAD
session_type: training
fixed_seed: 1

mode: imu_gcn
model_args:
  graph_node_format: node_per_sensor
  num_signals: 2
  gc_model: agcn
  inter_signal_back_connections: True

base_lr: 0.001
optimizer: ADAM
optimizer_args:
  weight_decay: 0.01

lr_scheduler: ca
# lr_scheduler_args:
#  T_max: 55

batch_size: 8
epochs: 50
